/* STYLISH CSS
 Exercise 5 of 8

HTML without styles is boring so this exercise will teach you how to use Stylus with Express on the fly.

Style the HTML from the "STATIC" exercise using Stylus middleware.
Stylus <https://github.com/stylus/stylus> generates .css files on-the-fly from .styl files.

Your solution should listen on the port supplied by process.argv[2] for
GET requests, one of which will be for main.css, which should be
automatically generated by your Stylus middleware. index.html and main.styl can be found in process.argv[3] (they are in the same directory).
 */
const express = require("express");
const stylus = require("stylus");

const app = express();
const port = process.argv[2];

// stylus middleware
app.use(stylus.middleware("public"));
app.use(express.static("public"));

app.listen(port);
